name = "Momenta"
uuid = "0ca3efaa-fb53-4d2f-87c7-6a9f57d6cfab"
version = "0.0.1"
authors = ["Dazhong Wu <dazhong.wu@udc.edu>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"


[extensions]
MomentaPlotsExt = "Plots"

[compat]
julia = "1.11"          # 直接指定最新版，彻底解决旧版兼容问题
BenchmarkTools = "1"    # 不要写 "1.6.3" 这么细，写 "1" 代表允许 1.x 的任何版本
CSV = "0.10"            # CSV 0.10 是目前的稳定系
DataFrames = "1"        # 允许 DataFrames 1.x
Distributions = "0.25"  
LinearAlgebra = "1"     # 标准库
Plots = "1"             # 关键！写 "1" 可以让解析器自动找最合适的版本，别写死 "1.41.2"
PrecompileTools = "1"
PrettyTables = "2, 3"   # 保持这个双版本兼容
Random = "1"

